In [2]:
import sys
sys.path.append('../../')
from utils.connection import postgres_connection
import pandas as pd

In [3]:
query = """
select * from healthcare.refined.appointments a 
"""

df = pd.read_sql(query, con=postgres_connection())

df

,appointment_id,patient_id,appointment_date,appointment_type,provider_id,date_insertion,day_of_week,time_since_last_appointment
0,1,37,2023-02-25,Checkup,4,2025-05-20 22:26:25.402163,Saturday,815
1,2,36,2023-03-10,Emergency,7,2025-05-20 22:26:25.402163,Friday,802
2,3,46,2023-04-02,Checkup,3,2025-05-20 22:26:25.402163,Sunday,779
3,4,1,2023-01-16,Consultation,6,2025-05-20 22:26:25.402163,Monday,855
4,5,42,2023-03-24,Emergency,4,2025-05-20 22:26:25.402163,Friday,788
...,...,...,...,...,...,...,...,...
415,101,51,2022-12-15,Checkup,4,2025-05-20 22:32:43.758023,Thursday,887
416,102,52,2023-01-20,Consultation,2,2025-05-20 22:32:43.758023,Friday,851
417,103,53,2023-01-10,Emergency,7,2025-05-20 22:32:43.758023,Tuesday,861
418,104,54,2023-02-05,Checkup,5,2025-05-20 22:32:43.758023,Sunday,835
419,105,55,2022-12-25,Consultation,3,2025-05-20 22:32:43.758023,Sunday,877